<a href="https://colab.research.google.com/github/nureeee/DeepLearning/blob/main/%ED%85%8D%EC%8A%A4%ED%8A%B8_%EB%B2%A1%ED%84%B0%ED%99%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
# n번 문서에 단어가 등장한 횟수
def term_frequency(term, document):
     tf = document.count(term) # term이 들어간 횟수
     
     return tf

def document_frequency(term, documents):
    df = 0
    for i in range(len(documents)):
        if term in documents[i]:
            df = df + 1

    # 방법2
    # df += term in documents 하면 값이 True와 False로 나와 True면 1이 된다.
    #방법3
    # for document in documents:
    #     if term in document:
    #         df += 1

    return df

def inverse_document_frequency(term, documents):
    from math import log
    # len(set(' '.join(documents).split())) n을 구하긴 한건데 형태소 분리가 되지 않은 것이라 무시
    idf = log(len(documents) / (1 + document_frequency(term, documents)))

    return idf

def tf_idf(term, documents, idx):
    result = term_frequency(term, documents[idx]) * inverse_document_frequency(term, documents)
    
    return result

In [46]:
docs = [
  '동해 물과 백두산이 마르고 닳도록 하느님이 보우하사 우리나라 만세. 무궁화 삼천리 화려 강산 대한 사람, 대한으로 길이 보전하세. 동해 가고 싶다',
  '남산 위에 저 소나무, 철갑을 두른 듯 바람 서리 불변함은 우리 기상일세. 무궁화 삼천리 화려 강산 대한 사람, 대한으로 길이 보전하세. 소나무 이쁘다',
  '가을 하늘 공활한데 높고 구름 없이 밝은 달은 우리 가슴 일편단심일세. 무궁화 삼천리 화려 강산 대한 사람, 대한으로 길이 보전하세. 가을 하늘 보고 싶다.',
  '이 기상과 이 마음으로 충성을 다하여 괴로우나 즐거우나 나라 사랑하세. 무궁화 삼천리 화려 강산 대한 사람, 대한으로 길이 보전하세. 나라를 사랑하자']

In [47]:
len(set(' '.join(docs).split()))

57

# tf-idf를 이용한 docs 분석

In [48]:
!pip install konlpy

Collecting konlpy
  Downloading https://files.pythonhosted.org/packages/85/0e/f385566fec837c0b83f216b2da65db9997b35dd675e107752005b7d392b1/konlpy-0.5.2-py2.py3-none-any.whl (19.4MB)
     |████████████████████████████████| 19.4MB 148kB/s
Requirement already satisfied: tweepy>=3.7.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (3.10.0)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (4.2.6)
Collecting beautifulsoup4==4.6.0
  Downloading https://files.pythonhosted.org/packages/9e/d4/10f46e5cfac773e22707237bfcd51bbffeaf0a576b0a847ec7ab15bd7ace/beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
     |████████████████████████████████| 92kB 9.4MB/s
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.19.5)
Collecting JPype1>=0.7.0
  Downloading https://files.pythonhosted.org/packages/98/88/f817ef1af6f794e8f11313dcd1549de833f4599abcec82746ab5ed086686/JPype1-1.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (448kB)
     |████████████████████████████████| 450kB 36.7MB/s
Collecting colorama
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Requirement already satisfied: requests[socks]>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from tweepy>=3.7.0->konlpy) (2.23.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from tweepy>=3.7.0->konlpy) (1.3.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from tweepy>=3.7.0->konlpy) (1.15.0)
Requirement already satisfied: typing-extensions; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->konlpy) (3.7.4.3)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (2021.5.30)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (3.0.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (1.7.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->tweepy>=3.7.0->konlpy) (3.1.1)
Installing collected packages: beautifulsoup4, JPype1, colorama, konlpy
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Successfully installed JPype1-1.3.0 beautifulsoup4-4.6.0 colorama-0.4.4 konlpy-0.5.2

In [49]:
from konlpy.tag import Okt
okt = Okt()

In [53]:
vocab = list(set(w for doc in docs for w in okt.nouns(doc)))

In [54]:
vocab

['데',
 '화려',
 '기상',
 '마르고',
 '이',
 '우리',
 '삼천리',
 '물',
 '나라',
 '사람',
 '보우',
 '달',
 '보고',
 '강산',
 '하느님',
 '동해',
 '대한',
 '남산',
 '만세',
 '불변',
 '일편단심',
 '저',
 '활',
 '우리나라',
 '하사',
 '소나무',
 '바람',
 '철갑',
 '보전',
 '하늘',
 '길이',
 '구름',
 '가을',
 '무궁화',
 '사랑',
 '위',
 '마음',
 '듯',
 '함',
 '충성',
 '서리',
 '가슴',
 '백두산']

In [55]:
vocab.sort()

In [56]:
vocab[:3]

['가슴', '가을', '강산']

In [63]:
import pandas as pd
import numpy as np

In [94]:
# docs1 = []
# docs2 = []
# docs3 = []
# docs4 = []

# for i in range(len(docs)):
#     for idx in range(len(dtm.columns)):
#         d = docs[i].count(str(dtm.columns[idx]))
#         if i == 0:
#             docs1.append(d)
#         elif i == 1:
#             docs2.append(d)
#         elif i == 2:
#             docs3.append(d)
#         else:
#             docs4.append(d)
        
#         docs[i].count(dtm.columns[idx])

In [ ]:
# 1절 
for vo in vocabs:
    term_frequency(vo, docs[0])

In [99]:
result = []
for doc in docs:
    result_tf = []
    for vo in vocab:
        result_tf.append(term_frequency(vo, doc))
    result.append(result_tf)

print(result)

[[0, 0, 1, 0, 0, 1, 1, 0, 0, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 3, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0], [0, 0, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 2, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0], [1, 2, 1, 1, 0, 1, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 2, 0, 0, 1, 1], [0, 0, 1, 0, 1, 1, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]]

### idf 결과를 데이터 프레임으로 확인

In [102]:
dtm = pd.DataFrame(result, columns=vocab)
dtm.head()

   가슴  가을  강산  구름  기상  길이  나라  남산  달  ...  저  철갑  충성  하느님  하늘  하사  함  화려  활
0   0   0   1   0   0   1   1   0  0  ...  0   0   0    1   0   1  0   1  0
1   0   0   1   0   1   1   0   1  0  ...  1   1   0    0   0   0  1   1  0
2   1   2   1   1   0   1   0   0  1  ...  0   0   0    0   2   0  0   1  1
3   0   0   1   0   1   1   2   0  0  ...  0   0   1    0   0   0  0   1  0

[4 rows x 43 columns]

In [103]:
result = []

for term in vocab:
    result.append(inverse_document_frequency(term, docs))

pd.DataFrame(result, index=vocab, columns=['idf'])

           idf
가슴    0.693147
가을    0.693147
강산   -0.223144
구름    0.693147
기상    0.287682
길이   -0.223144
나라    0.287682
남산    0.693147
달     0.693147
대한   -0.223144
데     0.693147
동해    0.693147
듯     0.693147
마르고   0.693147
마음    0.693147
만세    0.693147
무궁화  -0.223144
물     0.693147
바람    0.693147
백두산   0.693147
보고    0.693147
보우    0.693147
보전   -0.223144
불변    0.693147
사람   -0.223144
사랑    0.693147
삼천리  -0.223144
서리    0.693147
소나무   0.693147
우리    0.000000
우리나라  0.693147
위     0.693147
이    -0.223144
일편단심  0.693147
저     0.693147
철갑    0.693147
충성    0.693147
하느님   0.693147
하늘    0.693147
하사    0.693147
함     0.693147
화려   -0.223144
활     0.693147

### tf-df를 dataframe으로

In [104]:
result = []

for i in range(len(docs)):
    tf_idf_result = []
    for vo in vocab:
        tf_idf_result.append(tf_idf(vo, docs, i))

    result.append(tf_idf_result)

pd.DataFrame(result, columns=vocab)

         가슴        가을        강산  ...         함        화려         활
0  0.000000  0.000000 -0.223144  ...  0.000000 -0.223144  0.000000
1  0.000000  0.000000 -0.223144  ...  0.693147 -0.223144  0.000000
2  0.693147  1.386294 -0.223144  ...  0.000000 -0.223144  0.693147
3  0.000000  0.000000 -0.223144  ...  0.000000 -0.223144  0.000000

[4 rows x 43 columns]

# 텐서플로우 bow 구현하기

In [107]:
from tensorflow.keras.preprocessing.text import Tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
print(t.word_index)

{'무궁화': 1, '삼천리': 2, '화려': 3, '강산': 4, '대한': 5, '사람': 6, '대한으로': 7, '길이': 8, '보전하세': 9, '동해': 10, '싶다': 11, '소나무': 12, '우리': 13, '가을': 14, '하늘': 15, '이': 16, '물과': 17, '백두산이': 18, '마르고': 19, '닳도록': 20, '하느님이': 21, '보우하사': 22, '우리나라': 23, '만세': 24, '가고': 25, '남산': 26, '위에': 27, '저': 28, '철갑을': 29, '두른': 30, '듯': 31, '바람': 32, '서리': 33, '불변함은': 34, '기상일세': 35, '이쁘다': 36, '공활한데': 37, '높고': 38, '구름': 39, '없이': 40, '밝은': 41, '달은': 42, '가슴': 43, '일편단심일세': 44, '보고': 45, '기상과': 46, '마음으로': 47, '충성을': 48, '다하여': 49, '괴로우나': 50, '즐거우나': 51, '나라': 52, '사랑하세': 53, '나라를': 54, '사랑하자': 55}